export const PREDEFINED_ASSISTANT_CATEGORIES = [
	"FEATURED",
	"Ads",
	"AI",
	"Analytics",
	"Blog",
	"Business Intelligence",
	"Calendar",
	"Content Creation",
	"Customer Support",
	"Data Extraction",
	"Data Management",
	"Dev Ops",
	"Ecommerce",
	"Education",
	"Email",
	"Email Marketing",
	"Engineering",
	"Entrepreneur",
	"Finance",
	"Images",
	"Internet of Things",
	"Lead Generation",
	"Marketing",
	"Messaging",
	"Product",
	"Productivity",
	"Recruiting",
	"Research",
	"Sales",
	"Scraping",
	"SEO",
	"Social Media Management",
	"Spreadsheet",
	"Transcription",
	"Translation",
	"Voice",
];

export const AI_PLATFORMS = [
	"Reasoning Model",
	"Hybrid Reasoning Model",
	"Code Programming",
	"Fast Response",
	"Long Text Processing",
	"Web Search",
	"Search Tool",
	"Image and Video Recognition",
	"Mathematical Logic",
	"Financial Quantitative Analysis",
	"Write a Tweet",
	"Text Detection",
	"Translation",
	"Long-form Writing",
	"Emotional Companionship",
	"Chinese Friendly",
	"European Multilingual",
	"Middle East and Southeast Asia Multilingual",
	"Text-to-Image",
	"Image-to-Image",
	"Image-to-Video",
	"Text-to-Video",
	"Continuous Editing",
	"Text Recognition",
	"Commercial Design",
	"Anti-NSFW",
	"Smooth Motion",
	"All-in-One Assistant",
	"Audio Generation",
	"Text Proofreading",
];
